config/routes.rb
Rails.application.routes.draw do
  
  get 'main/home'

  root 'admin/welcome#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  namespace "admin" do
    resources :items
    resources :cities
    resources :units
    resources :categories
    resources :brands
    resources :cart_details
    resources :carts
    resources :users
  end

	get '/brands_suggestion', to: 'brands_suggestion#index'
	get '/validate_suggested_brand', to: 'validate_suggested_brand#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/unit.rb
class Unit < ApplicationRecord
	include ActiveModel::Validations

	validates :name, presence: true

	validates_with ValidateUnaccent, model: self
end

app/controllers/admin/units_controller.rb
class Admin::UnitsController < Admin::BaseController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]
  PAGE_SIZE = 10

  # GET /units
  # GET /units.json
  def index
    @page = (params[:page] || 0).to_i
    @keywords = params[:keywords]

    search = Search.new(@page, PAGE_SIZE, @keywords)
    @units, @number_of_pages = search.units_by_name
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to admin_units_url, notice: 'Unidad Creada.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to admin_units_url, notice: 'Unidad Actualizada.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to admin_units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/admin/units/_edit_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="card-body">
      <%= form_for @unit, url: {action: "update", namespace: "admin"} do |f| %>
        <% if unit.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

            <ul>
            <% unit.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.text_field :name, autofocus: true, placeholder: "Nombre", class: "form-control" %>
        </div>

        <%= f.submit "Aceptar", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/units/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="card-body">
      <%= form_for @unit, url: {action: "create", namespace: "admin"} do |f| %>
        <% if unit.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

            <ul>
            <% unit.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.text_field :name, autofocus: true, placeholder: "Nombre", class: "form-control" %>
        </div>

        <%= f.submit "Aceptar", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/units/_pager.html.erb
<nav>
	<ul class="pagination">
		<li class="previous <%= page == 0 ? 'disabled' : '' %>">
			<%= link_to_if page > 0, "&larr; Anterior".html_safe,
						admin_units_path(keywords: keywords, page: page - 1) %>
		</li>
		<li class="next <%= page == @number_of_pages ? 'disabled' : '' %>">
			<%= link_to_if page < @number_of_pages, "Siguiente &rarr;".html_safe,
						admin_units_path(keywords: keywords, page: page + 1) %>
		</li>
	</ul>
</nav>

app/views/admin/units/_results_search.html.erb
<table class="table">
  <thead>
    <tr>
      <%= render partial: "pager", locals: { keywords: @keywords, page: @page } %>
    </tr>
    <tr>
      <th>Nombre</th>
      <th>Fecha de Alta</th>
      <th>Fecha de Modificación</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.name %></td>
        <td><%= unit.created_at.strftime("%d/%m/%Y") %></td>
        <td><%= unit.updated_at.strftime("%d/%m/%Y") %></td>
        <td>
          <%= button_to edit_admin_unit_path(unit), {method: :get, class: "btn btn-info"} do %>
            <span class="fas fa-pencil-alt" aria-hidden="true"> </span> Editar
          <% end %>
        </td>
        <td>
          <%= button_to admin_unit_path(unit), { method: :delete, data: { confirm: '¿Está seguro?' }, class: "btn btn-danger" } do %>
            <span class="fas fa-trash" aria-hidden="true"> </span> Eliminar
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/units/edit.html.erb
<div class="container-fluid">
	<div class="row">
		<h1>Editar Unidad</h1>

		<%= render 'edit_form', unit: @unit %>

		<%= link_to 'Volver', admin_units_path %>

	</div>
</div>

app/views/admin/units/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Unidades</div>
  <div class="panel-body">
    <%= render partial: 'partials/search_form', locals: { search_entity: 'units', word: "Unidad" } %>
    <br>
    <div class="col-md-5 col-md-offset-5 col-sm-5 col-sm-offset-5">
      <p>
        <%= button_to new_admin_unit_path, {method: :get, class: "btn btn-success"} do %>
          <span class="fas fa-plus" aria-hidden="true"> </span> Nueva Unidad
        <% end %>
      </p>
    </div>
  </div>
  <%= render partial: 'results_search' %>
</div>

app/views/admin/units/new.html.erb
<div class="container-fluid">
	<div class="row">
		<h1>Nueva Unidad</h1>

		<%= render 'form', unit: @unit %>

		<%= link_to 'Volver', admin_units_path %>
	</div>
</div>

app/views/admin/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @unit.name %>
</p>

<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>