config/routes.rb
Rails.application.routes.draw do
  
  get 'main/home'

  root 'admin/welcome#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  namespace "admin" do
    resources :items
    resources :cities
    resources :units
    resources :categories
    resources :brands
    resources :cart_details
    resources :carts
    resources :users
  end

	get '/brands_suggestion', to: 'brands_suggestion#index'
	get '/validate_suggested_brand', to: 'validate_suggested_brand#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/brand.rb
class Brand < ApplicationRecord
	validates_with ValidateUnaccent, model: self
end

app/controllers/admin/brands_controller.rb
class Admin::BrandsController < Admin::BaseController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]
  PAGE_SIZE=5
  # GET /brands
  # GET /brands.json
  def index
    @page = (params[:page] || 0).to_i
    @keywords = params[:keywords]

    search = Search.new(@page, PAGE_SIZE, @keywords)
    @brands, @number_of_pages = search.brands_by_name
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to admin_brands_url, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to admin_brands_url, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to admin_brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:name)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/admin/brands/_edit_form.html.erb
<div class="container-fluid">
 <div class="row">
  <div class="card-body">
   <%= form_for @brand, url: {action: "update", namespace: "admin"}  do |f| %>
    <% if brand.errors.any? %>
     <div id="error_explanation">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
       <% brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
       <% end %>
      </ul>
     </div>
    <% end %>

    <div class="form-group">
     <%= f.text_field :name, autofocus: true, placeholder: "Nombre", class: "form-control" %>
    </div>

    <%= f.submit "Aceptar", class: "btn btn-success" %>
   <% end %>
  </div>
 </div>
</div>

app/views/admin/brands/_form.html.erb
<div class="container-fluid">
 <div class="row">
  <div class="card-body">
   <%= form_for @brand, url: {action: "create", namespace: "admin"}  do |f| %>
    <% if brand.errors.any? %>
     <div id="error_explanation">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
       <% brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
       <% end %>
      </ul>
     </div>
    <% end %>

    <div class="form-group">
     <%= f.text_field :name, autofocus: true, placeholder: "Nombre", class: "form-control" %>
    </div>

    <%= f.submit "Aceptar", class: "btn btn-success" %>
   <% end %>
  </div>
 </div>
</div>

app/views/admin/brands/_pager.html.erb
<nav>
 <ul class="pagination">
  <li class="previous <%= page == 0 ? 'disabled' : '' %>">
   <%= link_to_if page > 0, "&larr; Anterior".html_safe,
                  admin_brands_path(keywords: keywords, page: page - 1) %>
  </li>
  <li class="next <%= page == @number_of_pages ? 'disabled' : '' %>">
   <%= link_to_if page < @number_of_pages, "Siguiente &rarr;".html_safe,
                  admin_brands_path(keywords: keywords, page: page + 1) %>
  </li>
 </ul>
</nav>

app/views/admin/brands/_results_search.html.erb
<table class="table">
 <thead>
  <tr>
   <%= render partial: "pager", locals: { keywords: @keywords, page: @page } %>
  </tr>
  <tr>
   <th>Nombre</th>
   <th>Fecha de Alta</th>
   <th>Fecha de Modificación</th>
   <th colspan="2"></th>
  </tr>
 </thead>

 <tbody>
  <div id="brands">
   <% @brands.each do |brand| %>
    <tr>
     <td><%= brand.name %></td>
     <td><%= brand.created_at.strftime("%d/%m/%Y") %></td>
     <td><%= brand.updated_at.strftime("%d/%m/%Y") %></td>
     <td>
      <%= button_to edit_admin_brand_path(brand), {method: :get, class: "btn btn-info"} do %>
       <span class="fas fa-pencil-alt" aria-hidden="true"> </span> Editar
      <% end %>
     </td>
     <td>
      <%= button_to admin_brand_path(brand), { method: :delete, data: { confirm: '¿Está seguro?' }, class: "btn btn-danger" } do %>
       <span class="fas fa-trash" aria-hidden="true"> </span> Eliminar
      <% end %>
     </td>
    </tr>
   <% end %>
  </div>
 </tbody>
</table>

app/views/admin/brands/edit.html.erb
<div class="container-fluid">
 <div class="row">
  <h1>Editar Marca</h1>

  <%= render 'edit_form', brand: @brand %>

  <%= link_to 'Volver', admin_brands_path %>

 </div>
</div>

app/views/admin/brands/index.html.erb
<div class="panel panel-default">
 <div class="panel-heading">Marcas</div>
 <div class="panel-body">
  <%= render partial: 'partials/search_form', locals: { search_entity: 'brands', word: "Marca" } %>
  <br>
  <div class="col-md-5 col-md-offset-5 col-sm-5 col-sm-offset-5">
   <p>
    <%= button_to new_admin_brand_path, {method: :get, class: "btn btn-success"} do %>
     <span class="fas fa-plus" aria-hidden="true"> </span> Nueva Marca
    <% end %>
   </p>
  </div>
 </div>
 <%= render partial: 'results_search' %>
</div>

app/views/admin/brands/new.html.erb
<div class="container-fluid">
 <div class="row">
  <h1>Nueva Marca</h1>

  <%= render 'form', brand: @brand %>

  <%= link_to 'Volver', admin_brands_path %>
 </div>
</div>

app/views/admin/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @brand.name %>
</p>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>