config/routes.rb
Rails.application.routes.draw do
  
  get 'main/home'

  root 'admin/welcome#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  namespace "admin" do
    resources :items
    resources :cities
    resources :units
    resources :categories
    resources :brands
    resources :cart_details
    resources :carts
    resources :users
  end

	get '/brands_suggestion', to: 'brands_suggestion#index'
	get '/validate_suggested_brand', to: 'validate_suggested_brand#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
	validates_with ValidateUnaccent, model: self
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :cart_details, inverse_of: :cart, dependent: :destroy
	has_many :items, through: :cart_details
	belongs_to :user

	validates :date, presence: true

	accepts_nested_attributes_for :cart_details, reject_if: :cart_detail_rejectable?,
									allow_destroy: true

	enum state: [:draft, :confirmed]

	def total
		details = self.cart_details

		total = 0.0
		details.flat_map do |d|
			total += d.qty * d.price
		end
		total
	end

	private

		def cart_detail_rejectable?(att)
			att[:item_id].blank? || att[:qty].blank? || att[:price].blank? || att[:qty].to_f <= 0 || att[:price].to_f <= 0
		end
		
end

app/models/cart_detail.rb
class CartDetail < ApplicationRecord
	belongs_to :cart
	belongs_to :item

	validates :item_id, :qty, :price. presence: true

	accepts_nested_attributes_for :item

	def subtotal
		self.qty ? qty * unit_price : 0
	end

	def unit_price
		if persisted?
			price
		else
			item ? item.price : 0
		end
	end
end

app/models/category.rb
class Category < ApplicationRecord
	include ActiveModel::Validations
	validates :name, presence: true

	validates_with ValidateUnaccent, model: self
end

app/models/city.rb
class City < ApplicationRecord
	validates :code, presence: true, uniqueness: true
	validates :name, presence: true

	has_many :cities
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :brand
  belongs_to :unit
  belongs_to :category

  validates :description,:code,:brand_id, :unit_id, :category_id, :price, presence: true
  validates :code, uniqueness: true
  validates :stock,:price, length: { minimum: 0}
  validates :price, numericality: true
  validates :stock, numericality: { only_integer: true}

  def item_description
  	self.description + ( (self.brand != nil) ? ' ' + self.brand.name : '' )
  end

  def brand_name
  	if self.brand
  		self.brand.name
  	else
  		''
  	end
  end
end

app/models/search.rb
class Search
  def initialize(page, page_size, keywords, current_user = nil)
    @page = page
    @page_size = page_size
    @offset = page_size * page
    @keywords = keywords
    @current_user = current_user
  end


  def brands_by_name
    if @keywords.present?
        brands = Brand.where(name_condition).order(:name).offset(@offset).limit(@page_size)
        @number_of_records = Brand.where(name_condition).count
      else
        brands = Brand.order(:name).offset(@offset).limit(@page_size)
        @number_of_records = Brand.count
      end
      
      return brands, number_of_pages
  end

  def categories_by_name
    if @keywords.present?
        categories = Category.where(name_condition).order(:name).offset(@offset).limit(@page_size)
        @number_of_records = Category.where(name_condition).count
      else
        categories = Category.order(:name).offset(@offset).limit(@page_size)
        @number_of_records = Category.count
      end
      
      return categories, number_of_pages
  end

  def cities_by_name
    if @keywords.present?
        cities = City.where(name_condition).order(:name).offset(@offset).limit(@page_size)
        @number_of_records = City.where(name_condition).count
      else
        cities = City.order(:name).offset(@offset).limit(@page_size)
        @number_of_records = City.count
      end
      
      return cities, number_of_pages
  end

  def units_by_name
    if @keywords.present?
        units = Unit.where(name_condition).order(:name).offset(@offset).limit(@page_size)
        @number_of_records = Unit.where(name_condition).count
      else
        units = Unit.order(:name).offset(@offset).limit(@page_size)
        @number_of_records = Unit.count
      end
      
      return units, number_of_pages
  end

  def users_by_name
    if @keywords.present?
        users = User.where(name_condition).order(:name).offset(@offset).limit(@page_size)
        @number_of_records = User.where(name_condition).count
      else
        users = User.order(:name).offset(@offset).limit(@page_size)
        @number_of_records = User.count
      end
      
      return users, number_of_pages
  end

  def items_by_description
    if @keywords.present?
        items = Item.where(description_condition).order(:description).offset(@offset).limit(@page_size)
        @number_of_records = Item.where(description_condition).count
      else
        items = Item.order(:description).offset(@offset).limit(@page_size)
        @number_of_records = Item.count
      end
      
      return items, number_of_pages
  end

  def sales
    if @keywords.present?
        sales = Sale.where(sale_condition).order(number: :desc).offset(@offset).limit(@page_size)
        @number_of_records = Item.where(description_condition).count
      else
        sales = Sale.where(state: "confirmed").order(number: :desc).offset(@offset).limit(@page_size)
      @number_of_records = Sale.where(state: "confirmed").count
      end

    return sales, number_of_pages
  end

  private

  def name_condition
    name_condition = "unaccent(lower(name)) LIKE '%#{I18n.transliterate(@keywords.downcase)}%'"
  end

  def description_condition
    description_condition = "unaccent(lower(description)) LIKE '%#{I18n.transliterate(@keywords.downcase)}%'"
  end

  def sale_condition
    number_condition = "number = #{@keywords.to_i} and user_id = #{@current_user.id} and state = 1"
  end

  def number_of_pages
    number_of_pages = (@number_of_records % @page_size) == 0 ? 
                          @number_of_records / @page_size - 1 : @number_of_records / @page_size
  end
end

app/models/unit.rb
class Unit < ApplicationRecord
	include ActiveModel::Validations

	validates :name, presence: true

	validates_with ValidateUnaccent, model: self
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :carts
  belongs_to :city

  enum role: [ :member, :admin ]

  validates :username, :name, :last_name, :birthday, :genre, :city_id, presence: true
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
  	@items = Item.all
  end

  def set_layout
  	"landing"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource
		@resource ||= User.new
	end

	def resource_name
		:user
	end

	def resource_class
		User
	end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Shop</title>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="/web-fonts-with-css/css/fontawesome-all.css">
  <link href="/select2-4.0.6-rc.1/dist/css/select2.min.css" rel="stylesheet" />
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
 </head>

 <body class="<%= controller_name %> <%= action_name %>">

  <% if user_signed_in? %>
    <div class="wrapper">
		<%= render 'partials/sidebar' %>
    	<div id="content">
    		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			    <div class="container-fluid">

			        <div class="navbar-header">
			            <button type="button" id="sidebarCollapse" class="btn btn-info navbar-btn">
			                <i class="fas fa-align-left"></i>
			                <span>Alternar Barra</span>
			            </button>
			        </div>

			        <div class="collapse navbar-collapse" id="navbarSupportedContent">
			            <ul class="nav navbar-nav ml-auto">
			                <% if user_signed_in? %>

			                  <%= link_to "Logout", destroy_user_session_path,method: :delete, class: "margin-left medium btn btn-info navbar-btn" %>
			                <% end %>
			            </ul>
			        </div>
			    </div>
			</nav>
    		<%= render 'partials/alerts' %>
 
      		<%= yield %>	
    	</div> 
    	
     </div>
  <% else %>
   <br>
   <div class="row justify-content-md-center">
    <div class="col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4">
     <%= render 'partials/alerts' %>
    </div>
   </div>
 
   <%= yield %>
  <% end %>
  
  <script type="text/javascript">
     $(document).ready(function () {
         $('#sidebarCollapse').on('click', function () {
             $('#sidebar').toggleClass('active');
         });

         $('.alert').alert()
     });
 	</script>

  <%= yield :js %>
  <script src="/select2-4.0.6-rc.1/dist/js/select2.min.js"></script>
 </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Shop</title>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="/web-fonts-with-css/css/fontawesome-all.css">
  <link href="/select2-4.0.6-rc.1/dist/css/select2.min.css" rel="stylesheet" />
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
 </head>

 <body class="<%= controller_name %> <%= action_name %>">

  <% if user_signed_in? %>
    		<%= render 'partials/nav_land' %>
      <div id="content">
    		<%= render 'partials/alerts' %>
 
      		<%= yield %>	
    	</div> 
    	
     </div>
  <% else %>
   <br>
   <div class="row justify-content-md-center">
    <div class="col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4">
     <%= render 'partials/alerts' %>
    </div>
   </div>
 
   <%= yield %>
  <% end %>
  <script type="text/javascript">
     $(document).ready(function () {

         $('.alert').alert()
     });
  </script>
  <%= yield :js %>
  <script src="/select2-4.0.6-rc.1/dist/js/select2.min.js"></script>
 </body>
</html>

app/views/partials/_alerts.html.erb
<div class="container-fluid">
 <div class="row justify-content-md-center">
  <% if notice.present? %>
   <div class="alert alert-info alert-dismissible fade show col-12" role="alert">
   	<%= notice %>
   	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
   		<span aria-hidden="true">&times;</span>
   	</button>
   </div>
  <% end %>

  <% if alert.present? %>
   <div class="alert alert-danger alert-dismissible fade show col-12" role="alert">
   	<%= alert %>
   	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
   		<span aria-hidden="true">&times;</span>
   	</button>
   	</div>
  <% end %>
 </div>
</div>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" id="sidebarCollapse" class="btn btn-info navbar-btn">
                <i class="fas fa-align-left"></i>
                <span>Toggle Sidebar</span>
            </button>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <% if user_signed_in? %>

                  <%= link_to "Logout", destroy_user_session_path,method: :delete, class: "margin-left medium btn btn-info navbar-btn" %>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/partials/_nav_land.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary nav_land">
  <a class="navbar-brand" href="/main/home">Shop</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>

          <%= link_to "Logout", destroy_user_session_path,method: :delete, class: "margin-left medium btn btn-info navbar-btn" %>
        <% end %>
    </ul>
  </div>
</nav>

app/views/partials/_search_form.html.erb
<section class="search-form">
 <%= form_for search_entity, method: :get do |f| %>
  <div class="input-group">
   <%= label_tag :keywords, nil, class: "sr-only" %>
   <%= text_field_tag :keywords, nil, placeholder: "Buscar",
                       class: "form-control", value: "#{@keywords}" %>
   <span class="input-group-btn">
    <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
     <span class="fas fa-search"></span> Buscar <%= "#{word}" %>
    <% end %>
   </span>
  </div>
 <% end %>
</section>

app/views/partials/_sidebar.html.erb
<nav id="sidebar">
  <div class="sidebar-header">
      <h3>Tienda</h3>
      <strong>TN</strong>
  </div>

  <ul class="list-unstyled components">
      <li class="<%= current_page?(root_path) ? "active" : "" %>">
    <a href="<%= root_path %>">
      <span style="font-size:14px;" class=" hidden-xs showopacity"><i class="fas fa-sun"></i></span>
     Inicio
     
    </a>
   </li> 
 
   <li >
    <a href="#">
      <span style="font-size:14px;" class="-right hidden-xs showopacity"><i class="fas fa-shopping-cart"></i></span>
     Ventas
     
    </a>
   </li> 
 
   <li >
    <a href="#">
      <span style="font-size:14px;" class="-right hidden-xs showopacity"><i class="fas fa-book"></i></span>
     Contabilidad
     
    </a>
   </li>

   <li class="active">
    <a href="#almacenSubmenu" data-toggle="collapse" aria-expanded="false"><span style="font-size:14px;" class="-right hidden-xs showopacity"><i class="fas fa-home"></i></span>Almacén <i class="fas fa-caret-down"></i>
     
    </a>
    <ul class="collapse list-unstyled" id="almacenSubmenu">
     <li ><%= link_to 'Artículos', admin_items_path %></li>
    </ul>
   </li>

   <li>
    <a href="#configSubmenu" data-toggle="collapse" aria-expanded="false">
      <span style="font-size:14px;" class="-right hidden-xs showopacity"><i class="fas fa-wrench"></i></span>
     Configuración
     <i class="fas fa-caret-down hidden-xs showopacity"></i>
     
    </a>
    <ul class="collapse list-unstyled" id="configSubmenu">
     <li class="<%= current_page?(admin_categories_path) ? "active" : "" %>"><%= link_to 'Categorías', admin_categories_path %></li>
     <li class="<%= current_page?(admin_brands_path) ? "active" : "" %>"><%= link_to 'Marcas', admin_brands_path %></li>
     <li class="<%= current_page?(admin_units_path) ? "active" : "" %>"><%= link_to 'Unidades', admin_units_path %></li>
     <li class="<%= current_page?(admin_cities_path) ? "active" : "" %>"><%= link_to 'Localidades', admin_cities_path %></li>
     <li class="<%= current_page?(admin_users_path) ? "active" : "" %>"><%= link_to 'Usuarios', admin_users_path %></li>
     <li class="divider"></li>
     <li><a href="#">Respaldo</a></li>
    </ul>
   </li>
  </ul>

</nav>