config/routes.rb
Rails.application.routes.draw do
  
  get 'main/home'

  root 'admin/welcome#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  namespace "admin" do
    resources :items
    resources :cities
    resources :units
    resources :categories
    resources :brands
    resources :cart_details
    resources :carts
    resources :users
  end

	get '/brands_suggestion', to: 'brands_suggestion#index'
	get '/validate_suggested_brand', to: 'validate_suggested_brand#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
	include ActiveModel::Validations
	validates :name, presence: true

	validates_with ValidateUnaccent, model: self
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  PAGE_SIZE = 10

  # GET /categories
  # GET /categories.json
  def index
    @page = (params[:page] || 0).to_i
    @keywords = params[:keywords]

    search = Search.new(@page, PAGE_SIZE, @keywords)
    @categories, @number_of_pages = search.categories_by_name
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_categories_url, notice: 'Categoría creada.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_categories_url, notice: 'Categoría modficada.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_edit_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="card-body">
      <%= form_for @category, url: {action: "update", namespace: "admin"} do |f| %>
        <% if category.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

            <ul>
            <% category.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.text_field :name, autofocus: true, placeholder: "Nombre", class: "form-control" %>
        </div>

        <%= f.submit "Aceptar", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/categories/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="card-body">
      <%= form_for @category, url: {action: "create", namespace: "admin"} do |f| %>
        <% if category.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

            <ul>
            <% category.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.text_field :name, autofocus: true, placeholder: "Nombre", class: "form-control" %>
        </div>

        <%= f.submit "Aceptar", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/categories/_pager.html.erb
<nav>
	<ul class="pagination">
		<li class="previous <%= page == 0 ? 'disabled' : '' %>">
			<%= link_to_if page > 0, "&larr; Anterior".html_safe,
						admin_categories_path(keywords: keywords, page: page - 1) %>
		</li>
		<li class="next <%= page == @number_of_pages ? 'disabled' : '' %>">
			<%= link_to_if page < @number_of_pages, "Siguiente &rarr;".html_safe,
						admin_categories_path(keywords: keywords, page: page + 1) %>
		</li>
	</ul>
</nav>

app/views/admin/categories/_results_search.html.erb
<table class="table">
  <thead>
    <tr>
      <%= render partial: "pager", locals: { keywords: @keywords, page: @page } %>
    </tr>
    <tr>
      <th>Nombre</th>
      <th>Fecha de Alta</th>
      <th>Fecha de Modificación</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.created_at.strftime("%d/%m/%Y") %></td>
        <td><%= category.updated_at.strftime("%d/%m/%Y") %></td>
        <td>
          <%= button_to edit_admin_category_path(category), {method: :get, class: "btn btn-info"} do %>
            <span class="fas fa-pencil-alt" aria-hidden="true"> </span> Editar
          <% end %>
        </td>
        <td>
          <%= button_to admin_category_path(category), { method: :delete, data: { confirm: '¿Está seguro?' }, class: "btn btn-danger" } do %>
            <span class="fas fa-trash" aria-hidden="true"> </span> Eliminar
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/categories/edit.html.erb
<div class="container-fluid">
	<div class="row">
		<h1>Editar Categoría</h1>

		<%= render 'edit_form', category: @category %>

		<%= link_to 'Volver', admin_categories_path %>

	</div>
</div>

app/views/admin/categories/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Categorías</div>
  <div class="panel-body">
    <%= render partial: 'partials/search_form', locals: { search_entity: 'categories', word: "Categoría" } %>
    <br>
    <div class="col-md-5 col-md-offset-5 col-sm-5 col-sm-offset-5">
      <p>
        <%= button_to new_admin_category_path, {method: :get, class: "btn btn-success"} do %>
          <span class="fas fa-plus" aria-hidden="true"> </span> Nueva Categoría
        <% end %>
      </p>
    </div>
  </div>
  <%= render partial: 'results_search' %>
</div>

app/views/admin/categories/new.html.erb
<div class="container-fluid">
	<div class="row">
		<h1>Nueva Categoría</h1>

		<%= render 'form', category: @category %>

		<%= link_to 'Volver', admin_categories_path %>
	</div>
</div>

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>